public class MediaAritmetica {

    public static void main(String[] args){

        int[] nums = new int[4]
        nums[0] = 5;
        nums[1] = 7;
        nums[2] = 10;
        nums[3] = 3;

        int media = 0;
        for(int 1 = 0; i<nums.length; i++)
            media += nums[i];

        float total = (float)media / nums.length;

        System.out.println("A média é: "+total);
    }

}

    